Repository SpraxDev/Api.Sprax2013.de, pull requests merged in 2020-06, with the labels that each got.

#98 Release v0.5.0 (SkinDB, Optimizations, Cleanup)
  .sonarcloud.properties
  package-lock.json
  package.json
  resources/ai_models/README.md
  src/dbUtils.ts
  src/global.ts
  src/index-debug.ts
  src/index.ts
  src/routes/minecraft.ts
  src/routes/skindb.ts
  src/routes/skindb_frontend.ts
  src/routes/status.ts
  src/server.ts
  src/utils/ai_predict.ts
  src/utils/database.ts
  src/utils/modelRender.ts
  src/utils/utils.ts
  tsconfig.json
Labels: bug, enhancement

#119 Discard fragments with alpha
  src/utils/modelRender.ts
Labels: bug

#121 Fix Minecraft Skin Renderer
  src/routes/minecraft.ts
  src/utils/modelRender.ts
  src/utils/utils.ts
Labels: bug

#123 Support proxies for outbound connections
  package-lock.json
  package.json
  src/global.ts
  src/index.ts
  src/routes/minecraft.ts
  src/routes/skindb.ts
  src/utils/web.ts
Labels: enhancement

#125 Fix blocked servers
  package.json
  src/routes/minecraft.ts
Labels: bug

#135 MC: Render Blocks (#134)
  resources/rendering_models/block.obj
  src/routes/minecraft.ts
Labels: enhancement
